config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # Web Routes
  root 'pages#home'

  resources :rooms do
    member do
      get  :toggle_status
      get  :claim
      post :authenticate
    end
  end

  post '/sessions', to: 'sessions#create'
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: %i[new create edit update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  mount ActionCable.server, at: '/cable'

  # API Routes
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end
end

app/models/room.rb
# :nodoc:
class Room < ApplicationRecord
  belongs_to :user, optional: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  enum status: {
    temporary:    0,
    unrestricted: 1,
    restricted:   2
  }

  validates :name, presence: true,
                   length: { maximum: 100 },
                   uniqueness: { case_sensitive: false }

  after_create :make_room_public
  before_save  :create_hashed_password, if: :will_save_change_to_password?
  before_save  :update_status,          if: :will_save_change_to_password?
  before_save  :remove_password,        if: :unrestricted?

  def make_room_public
    return if user_id.nil?
    return unless password_is_blank?
    unrestricted!
  end

  def create_hashed_password
    self.password = password_is_blank? ? nil : BCrypt::Password.create(password)
  end

  def check_hashed_password(password_hash)
    BCrypt::Password.new(password_hash)
  end

  def update_status
    self.status = password_is_blank? ? 'unrestricted' : 'restricted'
  end

  def remove_password
    self.password = nil
  end

  def set_default_password
    self.password = BCrypt::Password.create('password')
  end

  private

  def password_is_blank?
    password.blank? || password.nil?
  end
end

app/controllers/rooms_controller.rb
require 'rest-client'
require 'json'

# :nodoc:
class RoomsController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!, only: %i[index edit new update]
  before_action :set_room,           only: %i[show edit update destroy
                                              toggle_status claim authenticate]
  rescue_from ActiveRecord::RecordNotFound, with: :room_not_found
  rescue_from SocketError, with: :socket_error

  def authenticate
    password_hash = @room.check_hashed_password(@room.password)

    if password_hash == params[:password]
      flash[:success] = "You are now in the room: #{@room.name}"
      redirect_to action: 'show', password: password_hash
    else
      flash[:notice] = 'You entered the incorrect password!'
    end
  end

  def index
    @rooms = @user.rooms
  end

  def new
    @room = Room.new
  end

  # TODO refactor this into an API controller
  def create
    require "opentok"
    opentok = OpenTok::OpenTok.new "46717132", "62ae1551b8376bdf4f2f05c326831e21ce71a00b"
    session = opentok.create_session
    params[:room][:session_id] = session.session_id
    @room = Room.new(room_create_params)
    respond_to do |format|
      if @room.save
        format.html do
          flash[:success] = 'You created a room!'
          redirect_to @room
        end

        format.json { render :show, status: :created, location: @room }
      else
        format.html do
          flash[:notice] = 'Sorry, that room is taken!'
          redirect_to root_path
        end

        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    unless @room.user == current_user
      flash[:notice] = 'You cannot edit this room'
      redirect_to @room
    end
  end

  def update
    if @room.update_attributes(room_update_params)
      flash[:success] = 'You added a password to this room'
    else
      flash[:notice] = 'Something went wrong'
    end

    redirect_to @room
  end

  def show
    ask_for_password(@room, params[:password]) unless
      @room.password.nil? ||
      @room.user == current_user

    if @room.password
      flash.now[:notice] = 'This is a password protected room'
    end

    return if Rails.env == 'test'
    # XirsysCredentialsJob.perform_later(@room.slug)



require "opentok"

opentok = OpenTok::OpenTok.new "46717132", "62ae1551b8376bdf4f2f05c326831e21ce71a00b"

@token = opentok.generate_token @room.session_id

# 1_MX40NjcxNzEzMn5-MTU4ODU5MTA5ODMxOH54cmF2dnk3WUREOTVPcGxwT3ZZVERaZld-UH4



  end

  def toggle_status
    if (@user.is_a? GuestUser) ||
       (@room.user != @user) ||
       (params[:status] == 'restricted')
      flash[:notice] = 'You are not allowed to do that!'
      redirect_to @room
      return
    end

    @room.status = params[:status]
    @room.save
    flash[:notice] = 'Room status updated'
    redirect_to @room
  end

  def claim
    if @room.user || (@user.is_a? GuestUser)
      flash[:notice] = 'You are not allowed to do that!'
      redirect_to @room
      return
    end

    claim_room
  end

  private

  def set_user
    @user = current_user
  end

  def set_room
    @room = Room.friendly.find(params[:id])
  end

  def room_create_params
    params.require(:room).permit(:name, :user_id, :password,:session_id)
  end

  def room_update_params
    params.require(:room).permit(:password)
  end

  def ask_for_password(room, password = nil)
    render 'rooms/authenticate' unless password == room.password
  end

  def claim_room
    @room.user   = current_user
    @room.status = 'unrestricted'
    @room.save
    flash[:success] = 'Room claimed'
    redirect_to @room
  end

  def room_not_found
    flash[:notice] = 'That room does not exist, would you like to create it?'
    redirect_to new_room_path
  end

  def socket_error
    flash[:notice] = 'TODO: Something went wrong with the WebRTC stuff'
    redirect_to root_path
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_auth_form.html.erb
<%= form_tag authenticate_room_path do %>
  <div class="form-group">
    <h2 class="text-secondary">Password</h2>
    <%= password_field_tag :password, nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit_tag "Enter Room", class: "btn btn-salmon btn-block" %>
  </div>
<% end %>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <% unless @room.name %>
    <div class="form-group">
      <h2 class="text-secondary">Room Name</h2>
      <%= f.text_field :name, class: "form-control", required: true , maxlength: 25%>
    </div>
  <% end %>

  <div class="form-group">
    <h2 class="text-secondary">Room Password <small><em>optional</em></small></h2>
    <%= f.text_field :password, class: "form-control" , value: ""%>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.submit 'Save', class: "btn btn-salmon btn-block" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<li class="list-group-item">
  <%= link_to room.name, room %>
</li>

app/views/rooms/authenticate.html.erb
<div class="container h-75 w-100">
  <div class="row h-100 justify-content-center align-items-center">
      <div class="col-lg-6 text-center">
        <h1>Enter Room Password</h1>
        <div class="card mt-3 mb-3 p-5">
          <div class="card-block">
            <%= render 'auth_form' %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container h-75 w-100">
  <div class="row h-100 justify-content-center align-items-center">
      <div class="col-lg-6 text-center">
        <h1>Room Settings</h1>
        <div class="card mt-3 mb-3 p-5">
          <div class="card-block">
            <%= render 'form' %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row h-100 justify-content-center">
    <div class="col-lg-6 text-center">
      <h1>Your Rooms</h1>

      <ul class="list-group mb-3">
        <%= render @rooms %>
      </ul>

      <%= link_to "Create a Room", new_room_path, class: "btn btn-salmon" %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container h-75 w-100">
  <div class="row h-100 justify-content-center align-items-center">
      <div class="col-lg-6 text-center">
        <h1>Create a Room</h1>
        <div class="card mt-3 mb-3 p-5">
          <div class="card-block">
            <%= render 'form' %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/rooms/show.html.erb
<style type="text/css">
      .video_con_buttons{
        text-align: right;
      }
      .video_con_buttons ul li {
        display: inline-block;
        padding: 0 5px;
      }
      .video_con_buttons ul li button {
          border: none;
          background: transparent;
          padding: 0;
        }
        .video_con_buttons ul li button img {
          height: 50px;
        }

        .more_option ul li {
          display: block;
          border-bottom: 1px solid #ddd;
        }
        .more_option .dropdown-menu li:last-child {
          border-bottom: none;
        }
        .more_option .dropdown-menu {
          right: 0px;
          left: inherit !important;
        }
        .more_option .dropdown-toggle:after {
          display: none;
        }
@-webkit-keyframes marquee {
    0% {text-indent:100%;}
    100% {text-indent:-10%}
}

input.marquee {
  -webkit-animation: marquee 5s infinite;
  -webkit-animation-timing-function: linear;
  }


    </style>



<div class="container">

  <div class="row justify-content-center mb-3">
      <div class="col-md-6">
    <% if current_user && @room.user == current_user %>
        <div class="input-group">
          <input
            type="text"
            id="copy-room-name"
            class="form-control marquee"
            value='<%= "#{request.base_url}/rooms/#{@room.slug}" %>'
          >
          <span class="input-group-btn">
            <button class="btn btn-secondary" type="button" id="copy-button">Click to Copy</button>
          </span>
        </div>
    <% end %>
      </div>
    <div class="col-md-6">
      <div class="video_con_buttons">
          <ul>
            <li id="join-btn-container">
                <button onclick="handleJoinSession()" >
                  <%= image_tag("join_call.png") %>
                </button>
            </li>
            <li id="leave-btn-container">
                <button onclick="handleLeaveSession()">
                  <%= image_tag("leave_call.png") %>
                </button>
            </li>
            <li id="stopvideo"  style="display: none">
              <button >
                <%= image_tag("video_stop.png") %>
              </button>
            </li>

            <li id="startvideo"  style="display: none">
              <button >
                <%= image_tag("video_enable.png") %>
              </button>
            </li>

            <li>
              <div class="more_option">
                  <div class="dropdown">
                    <button class="dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                      <%= image_tag("more.png") %>
                    </button>

<ul class="dropdown-menu">
  <% present @room do |room_presenter| %>
    <%= room_presenter.register_link(current_user) %>
    <%= room_presenter.claim_room_link(current_user) %>
    <%= room_presenter.toggle_status_link(current_user) %>
    <%= room_presenter.room_settings_link(current_user) %>
  <% end %>
</ul>



                  </div>
                </div>
            </li>
          </ul>
        </div>
    </div>



  </div>

  <div class="row">
    <div class="col-md-12">
      <span id="room-name" data-room='<%= @room.slug %>'></span>
      <span id="currentUser" data-email='<%= @user.email %>'></span>
      <div id="remoteViewContainer"></div>





    <div id="videos" style="display: none">
        
        <div id="subscribers">
          <div id="publisher"></div>


        </div>
    </div>

    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script src="client.js"></script>




<!--       <div id="localViewContainer">
        <video id="selfView" autoplay></video>
      </div> -->
    </div>
  </div>

</div>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>


<script type="text/javascript">
  var sessionId = "<%= @room.session_id %>";
  var token = "<%= @token %>";
  // var token = "T1==cGFydG5lcl9pZD00NjcxNzEzMiZzaWc9ZjgzZWY1MGFiNjgzYTM3OTk0YWYwMGUzODkwMTg3ZDljNjkwOWFkMTpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTFfTVg0ME5qY3hOekV6TW41LU1UVTRPRFU1TVRRMU1UZzVObjVMZFRJd1VYTXhVR2w1V0hNdmRqRTNWMUJpTldKU1lXVi1VSDQmY3JlYXRlX3RpbWU9MTU4ODYwMTIxOSZub25jZT0wLjM0NzE3Mzc2MjQ0NzM3MTY0";
  var api_key = "46717132";
  var apiKey = "46717132";
  var name ;
  <%- if @room.user == current_user %>
    name = "ORGANIZER";
  <% else %>
      name = "";
  <% end %>

</script>


<script type="text/javascript">
  
var btnEnter = document.getElementById('enter');
var stopvideo = document.getElementById('stopvideo');
var startvideo = document.getElementById('startvideo');
var divSelectRoom = document.getElementById('selectRoom');
var divVideos = document.getElementById('videos');
const joinBtnContainer = document.getElementById("join-btn-container");
const leaveBtnContainer = document.getElementById("leave-btn-container");
var session;
var tmp;


function initializeSession() {

    // divSelectRoom.style = "display: none";
    divVideos.style = "display: block";

    session = OT.initSession(apiKey, sessionId);

    // Subscribe to a newly created stream
    session.on('streamCreated', function (event) {
        console.log("streamCreated");
        console.log(event);
        session.subscribe(event.stream, 'subscribers', {
            insertMode: 'append',
            width: '360px',
            height: '240px',
            name: "",
            videoDisabledDisplayMode: true,
            allow: "microphone; camera"
        }, handleError);
    });
    // Create a publisher
    var publisher = OT.initPublisher('publisher', {
        insertMode: 'append',
        width: '360px',
        height: '240px',
        name: name,
        videoDisabledDisplayMode: true,
        allow: "microphone; camera"
    }, handleError);

    console.log(publisher);
    tmp = publisher;

    // Connect to the session
    session.connect(token, function (error) {
        // If the connection is successful, publish to the session
        if (error) {
            handleError(error);
        } else {
            session.publish(publisher, handleError);
        }
    });

    stopvideo.style.display = "initial";

}

// Handling all of our errors here by alerting them
function handleError(error) {
    console.log("errorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
    console.log(error);

    if (error) {
      if(error.code == 1500){
        alert("You neeed to accept the camera service to join the video call");
          // alert(error.message);
          joinBtnContainer.style.display = "initial";
          leaveBtnContainer.style.display = "none";
          stopvideo.style.display = "none";
          startvideo.style.display = "none";
        // initializeSession();

      }else{
        alert(error.message);
      }


    }
}



</script>


<script type="text/javascript">
  function handleJoinSession(){
    initializeSession();

    joinBtnContainer.style.display = "none";
    leaveBtnContainer.style.display = "initial";



  }



  function handleLeaveSession(){

    joinBtnContainer.style.display = "initial";
    leaveBtnContainer.style.display = "none";

    session.disconnect();



  }

stopvideo.onclick = function () {
  videoOff();


}

startvideo.onclick = function(){
  videoon();
}


  function videoon(){
    tmp.publishVideo(true);

    stopvideo.style.display = "initial";
    startvideo.style.display = "none";




  }

  function videoOff(){
    tmp.publishVideo(false);

    stopvideo.style.display = "none";
    startvideo.style.display = "initial";


  }


// subscriber.on("videoDisabled", function(event) {
//   // You may want to hide the subscriber video element:
//   domElement = document.getElementById(subscriber.id);
//   domElement.style["visibility"] = "hidden";

//   // You may want to add or adjust other UI.
// });

document.getElementById("copy-button").addEventListener("click", function(e) {
  e.preventDefault();

  var copied;
  document.getElementById("copy-room-name").select();

  try {
    copied = document.execCommand("copy");
  } catch (e) {
    copied = false;
  }

  if (copied) {
    document.getElementById("copy-button").innerHTML = "Saved to Clipboard!"
  }
});



</script>


<style type="text/css">
  
.OT_subscriber{
  display: inline-block;
}

#publisher, #subscribers {
    /*display: inline-block;*/
    float: left;
}



.OT_subscriber, .OT_publisher {
    border-radius: 20px;
    margin-right: 8px;
    box-shadow: 8px 0px 20px rgba(0,0,0,0.2);
    margin-bottom: 8px;
}

#stopvideo {
  margin-top: 10px;
}




</style>

<script type="text/javascript">
  
// OT.checkScreenSharingCapability(function(response) {
//   if(!response.supported || response.extensionRegistered === false) {
//     // This browser does not support screen sharing
//     alert("no screen sharing available");
//   }
// });





</script>